import os


REDIS_HOST = os.getenv("REDIS_HOST")
REDIS_PORT = int(os.getenv("REDIS_PORT"))
RPC_URL = os.getenv("RPC_URL")
ETHERSCAN_API_KEY = os.getenv("ETHERSCAN_API_KEY")
ETH_UNISWAPV3_USDC_ETH_POOL_ADDR = "0x88e6A0c2dDD26FEEb64F039a2c41296FcB3f5640"
